frameworkVersion: '~4.17.1'
service: w360-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: dev
  memorySize: 512
  timeout: 30
  deploymentBucket:
    name: w360-api-dev-deployment-bucket  

functions:
  W360:
    handler: app.handler
    name: W360
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - .git/**
    - README.md
    - scripts/**
    - config/**
    - aws/**
