frameworkVersion: '~4.17.1'
service: w360-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stackName: w360-api-dev
  stage: dev
  memorySize: 512
  timeout: 30
  deploymentBucket:
    name: w360-api-dev-deployment-bucket

functions:
  W360:
    handler: app.handler
    name: W360-dev
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

# ✅ Only offline plugin
plugins:
  - serverless-offline

# ✅ Enable built-in esbuild (optional, useful for faster builds)
package:
  patterns:
    - '!node_modules/**'
    - '!scripts/**'
    - '!aws/**'
    - '!README.md'
    - '!**/.git/**'
